name: Lua Tests

on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "lua/**"
            - "tests/spec/**"
            - ".busted"
            - "Makefile"
    pull_request:
        paths:
            - "lua/**"
            - "tests/spec/**"
            - ".busted"
            - "Makefile"

jobs:
    test:
        name: Run Lua unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Lua environment for Neovim
              uses: notomo/action-setup-nvim-lua@v2

            - name: Install vusted
              run: luarocks install vusted

            - name: Install Neovim
              uses: rhysd/action-setup-vim@v1
              id: nvim
              with:
                  neovim: true
                  version: stable

            - name: Run tests
              env:
                  VUSTED_NVIM: ${{ steps.nvim.outputs.executable }}
              run: make test
